package com.luyao.crowd.pojo;

public class Auth {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.name
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.title
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_auth.category_id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    private Integer categoryId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.id
     *
     * @return the value of t_auth.id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.id
     *
     * @param id the value for t_auth.id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.name
     *
     * @return the value of t_auth.name
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.name
     *
     * @param name the value for t_auth.name
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.title
     *
     * @return the value of t_auth.title
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.title
     *
     * @param title the value for t_auth.title
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_auth.category_id
     *
     * @return the value of t_auth.category_id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public Integer getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_auth.category_id
     *
     * @param categoryId the value for t_auth.category_id
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    public Auth(Integer id, String name, String title, Integer categoryId) {
        this.id = id;
        this.name = name;
        this.title = title;
        this.categoryId = categoryId;
    }

    public Auth() {
    }

    @Override
    public String toString() {
        return "Auth{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", title='" + title + '\'' +
                ", categoryId=" + categoryId +
                '}';
    }
}