package com.luyao.crowd.mapper;

import com.luyao.crowd.pojo.Auth;
import com.luyao.crowd.pojo.AuthExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AuthMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    long countByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int deleteByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int insert(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int insertSelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    List<Auth> selectByExample(AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    Auth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int updateByExampleSelective(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int updateByExample(@Param("record") Auth record, @Param("example") AuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int updateByPrimaryKeySelective(Auth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_auth
     *
     * @mbg.generated Sun Apr 03 18:23:07 CST 2022
     */
    int updateByPrimaryKey(Auth record);

    /**
     * 获取角色已分配的权限
     * @param roleId
     * @return
     */
    List<Integer> selectAssignedAuthIdByRoleId(Integer roleId);

    /**
     * 删除角色的权限
     * @param roleId
     */
    void deleteOldRelationship(Integer roleId);

    /**
     * 增加角色的权限
     * @param roleId
     * @param authIdList
     */
    void insertNewRelationship(@Param("roleId") Integer roleId, @Param("authIdList") List<Integer> authIdList);
}